services:
  db:
    image: postgis/postgis:16-3.4
    container_name: tracking-postgis
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Phamnam99
      POSTGRES_DB: tracking
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tracking"]
      interval: 10s
      timeout: 5s
      retries: 10
# add pgadmin service
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: tracking-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" # Truy cập pgAdmin tại http://localhost:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin # Volume để lưu trữ cài đặt pgAdmin
    depends_on:
      db:
        condition: service_healthy # Chờ cho đến khi 'db' sẵn sàng
  redis:
    image: redis:7-alpine
    container_name: tracking-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"        # UI chạy trên 5540
    volumes:
      - redisinsight_data:/data
    # không cần env gì thêm

volumes:
  pg_data:
  redis_data:
  redisinsight_data:
  pgadmin_data:
